#
# Travis CI configuration file for the IPP sample project.
#
# Copyright Â© 2018 by the IEEE-ISTO Printer Working Group.
#
# Licensed under Apache License v2.0.  See the file "LICENSE" for more
# information.
#

language: c

matrix:
  include:
    # Linux-specific build stuff
    - os: linux
      script:
        - docker build -t ippsample .

    # macOS-specific build stuff
    - os: osx
      osx_image: xcode9.4


notifications:
  email:
    recipients:
      - istopwg-ippsample-dev@pwg.org
    on_success: always # default: change
    on_failure: always # default: always      