language: cpp
compiler: gcc
sudo: require
dist: trusty

install:
    - sudo apt-get -y install autoconf build-essential avahi-daemon avahi-utils libavahi-client-dev libgnutls28-dev libjpeg-dev libnss-mdns libpng-dev zlib1g-dev

script:
  - ./configure --prefix=/usr
  - make -j$(nproc)
  - make BUILDROOT=$(readlink -f appdir) install ; find appdir/
  - rm -rf appdir/usr/include/cups/ # Do not bundle developer stuff
  - sudo mv  ./appdir/usr/sbin/* ./appdir/usr/bin/ ; rm -rf ./appdir/usr/sbin/ # AppRun does not put usr/sbin/ on $PATH
  - mkdir -p ./appdir/usr/share/applications/ ; cp appimage/ippserver.desktop ./appdir/usr/share/applications/
  - mkdir -p ./appdir/usr/share/icons/hicolor/256x256/apps/ ; cp appimage/printer.png ./appdir/usr/share/icons/hicolor/256x256/apps/
  - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt*.AppImage
  - ./linuxdeployqt*.AppImage --appimage-version
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -bundle-non-qt-libs
  - # In addition to the main executable, we have additional ones to process
  - ./linuxdeployqt*.AppImage ./appdir/usr/bin/PPfind -bundle-non-qt-libs
  - ./linuxdeployqt*.AppImage ./appdir/usr/bin/PPproxy -bundle-non-qt-libs
  - ./linuxdeployqt*.AppImage ./appdir/usr/bin/PPtool -bundle-non-qt-libs
  - # Bundle examples/ and test/
  - mkdir -p ./appdir/usr/share/cups/ipptool/ ; cp -r examples/* test/* ./appdir/usr/share/cups/ipptool/
  - # Generate AppImage
  - ./linuxdeployqt*.AppImage --appimage-extract
  - rm ./appdir/AppRun ; cp appimage/AppRun appdir/ ; chmod a+x ./appdir/AppRun # Replace symlink with custom script
  - PATH=./squashfs-root/usr/bin:$PATH ./squashfs-root/usr/bin/appimagetool ./appdir/

after_success:
  - find ./appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
  - curl --upload-file ./ippserver*.AppImage https://transfer.sh/ippsample-git.$(git rev-parse --short HEAD)-x86_64.AppImage
