name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-linux-static-openssl:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive
    - name: Update build environment
      run: sudo apt-get update --fix-missing -y
    - name: Install prerequisites
      run: sudo apt-get install -y avahi-daemon cppcheck libavahi-client-dev libjpeg-dev libpam-dev libpng-dev libssl-dev libusb-1.0-0-dev zlib1g-dev
    - name: Configure
      env:
        CC: /usr/bin/gcc
      run: ./configure --enable-debug --enable-maintainer --enable-static --disable-shared --with-tls=openssl
    - name: Make
      run: make
    - name: Test
      run: mkdir -p $HOME; whoami; make test || cat test/test-ippserver.log

  build-linux-shared-gnutls:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive
    - name: Update build environment
      run: sudo apt-get update --fix-missing -y
    - name: Install prerequisites
      run: sudo apt-get install -y avahi-daemon cppcheck libavahi-client-dev libgnutls28-dev libjpeg-dev libpam-dev libpng-dev libusb-1.0-0-dev zlib1g-dev
    - name: Configure
      env:
        CC: /usr/bin/gcc
      run: ./configure --enable-debug --enable-maintainer --enable-static --enable-shared --with-tls=gnutls
    - name: Make
      run: make
    - name: Test
      run: mkdir -p $HOME; whoami; make test || cat test/test-ippserver.log

  build-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive
    - name: Install prerequisites
      run: brew install cppcheck openssl@3
    - name: Configure
      run: ./configure --enable-debug --enable-maintainer --enable-static --disable-shared
    - name: Make
      run: make
    - name: Test
      run: mkdir -p $HOME; whoami; make test || cat test/test-ippserver.log

  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive
    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v2
    - name: Restore NuGet packages
      run: cd vcnet; nuget restore ippsample.sln; cd ..\libcups\vcnet; nuget restore libcups.sln; cd ..\pdfio; nuget restore
    - name: Build
      run: cd vcnet; msbuild ippsample.sln
